# Freearchy zsh + Oh My Zsh entrypoint. Add personal config below.

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="freearchy"
plugins=(git)

[[ -f $ZSH/oh-my-zsh.sh ]] && source "$ZSH/oh-my-zsh.sh"

if command -v mise >/dev/null; then
  eval "$(mise activate zsh)"
fi

if [[ $- == *i* ]] && [[ ${TERM:-} != dumb ]] && command -v starship >/dev/null; then
  eval "$(starship init zsh)"
fi

if command -v zoxide >/dev/null; then
  eval "$(zoxide init zsh)"
fi

if command -v fzf >/dev/null; then
  [[ -f /usr/share/fzf/key-bindings.zsh ]] && source /usr/share/fzf/key-bindings.zsh
  [[ -f /usr/share/fzf/completion.zsh ]] && source /usr/share/fzf/completion.zsh
fi

if command -v eza >/dev/null; then
  alias ls='eza -lh --group-directories-first --icons=auto'
  alias lsa='ls -a'
  alias lt='eza --tree --level=2 --long --icons --git'
  alias lta='lt -a'
fi

alias ..='cd ..'
alias ...='cd ../..'
alias g='git'
alias n='nano'
